### ISSUE TITLE
EnumerateUserSubscribedFiles support.

### ISSUE THREAD

**Issue by BTFighter** [otavepto/gbe_fork#23]
Human Fall Flat cannot use workshop maps and skins due to ISteamRemoteStorage_EnumerateUserSubscribedFiles() not implemented yet.

With Rivals of Aether, you can use mods but can't use them either on LAN or Online due to the game thinking it's a local mod.

**Comment by Kola124** [comment]
If that is problem then it might fix many games refusing to load mods at all. Few of my offenders are call to arms, man of war, serious sam and rise of nations. RoN cant start without validating mods at all.

**Comment by Detanup01** [comment]
could do it. it just ned to get all the published file things

mods.json
ID will be data.m_rgPublishedFileId
if time_added exist use that if not fallback to current time at epoch SECONDs

**Comment by BTFighter** [comment]
Only have Rivals of Aether installed as of now, so I'll test this game in the meantime.

Do I need to do anything else besides placing the mod in the mod folder? It still thinks it's a local mod.

**Comment by Detanup01** [comment]
add a mods.json with the mod id from steamcommunity. you can check the json

**Comment by BTFighter** [comment]
Doesn't work.
![image](https://github.com/otavepto/gbe_fork/assets/45516471/e28fb3a4-e82d-46e1-a247-e3dcbd297ea9)

Here's the mods.json. It's just one mod. I can't fill some since I don't know where to grab those.
```
{
    "1867608473": {
        "title": "Kris",
        "description": "The legendary human lightener joins the fray! Entering from the Dark World, and into the Land of Aether, Kris, from Deltarune, is ready to face any challenge that comes in their way.",
        "steam_id_owner": 76561198082364910,
        "time_created": 1554997000,
        "time_updated": 1554997000,
        "time_added": 1554997000,
        "tags": "Maps, exampleTag, exampleTag2",
        "primary_filename": "test.sav",
        "primary_filesize": 1000000,
        "preview_filename": "test.png",
        "preview_filesize": 1000000,
        "workshop_item_url": "https://steamcommunity.com/sharedfiles/filedetails/?id=1867608473",
        "upvotes": 1,
        "downvotes": 0,
        "num_children": 0,
        "path": "C:\\Games\\Rivals of Aether\\steam_settings\\mods\\1867608473",
        "preview_url": "file://C://Games//Rivals of Aether//steam_settings//mods//1867608473//preview.jpg",
        "score": 0.7
    }
}
```

**Comment by Kola124** [comment]
Serious Sam gives this error no workshop stuff is loaded,
![image](https://github.com/otavepto/gbe_fork/assets/39947399/4b35bd10-551a-4d8b-8f1e-c18d65d542e5)
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/13846014/STEAM_LOG.txt)


Tabletop simulator still gives this error
![image](https://github.com/otavepto/gbe_fork/assets/39947399/7ba0275d-e65b-4abb-af28-aa01ecfe7028)
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/13846006/STEAM_LOG.txt)


Call to Arms still empty
![image](https://github.com/otavepto/gbe_fork/assets/39947399/e2a73364-6e3d-4c4d-b1f2-caa2375949ab)
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/13846002/STEAM_LOG.txt)


Included log for every game if that helps in any way

**Comment by Kola124** [comment]
> I can't fill some since I don't know where to grab those.

http://steamworkshop.download/ and https://catalogue.smods.ru/, skymods can even update mods on request.

**Comment by BTFighter** [comment]
> http://steamworkshop.download/ and https://catalogue.smods.ru/, skymods can even update mods on request.

Sorry, wasn't clear on my message. I meant on mod info like time_added or time_updated, if that's even needed.

**Comment by Kola124** [comment]
Most of those things are not needed since everything has default value.

**Comment by Detanup01** [comment]
TableTop using others than I said what I implemented .

To Look at:
Steam_UGC::GetQueryUGCResult 
Steam_UGC::CreateQueryUserUGCRequest
Steam_UGC::SendQueryUGCRequest
Steam_Remote_Storage::UGCDownload
Steam_UGC::ReleaseQueryUGCRequest

**Comment by Detanup01** [comment]
Thanks for testing will try to look at these and trying some stuff.
Probably gonna update the repo for this change.

**Comment by Detanup01** [comment]
Nice, will test in weekend or monday.

@Kola124 Please re-check your mods and your games with the newest build!
Thanks!

**Comment by Kola124** [comment]
I have some unexpected electric construction work to do last few days, will try to test in evening

**Comment by Kola124** [comment]
Rise of Nations: still cant load into game

1. Test with declared primary file:
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/14002885/STEAM_LOG.txt)
![image](https://github.com/otavepto/gbe_fork/assets/39947399/6415c67f-8819-4ec7-8b57-f604d17d902d)

2. Test without declared primary file:
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/14002893/STEAM_LOG.txt)
![image](https://github.com/otavepto/gbe_fork/assets/39947399/dcb1427a-da0c-4d38-8df1-557616d9661d)

3. Might be helpfull that it is trying to validate mods even when they are not present:
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/14002904/STEAM_LOG.txt)
![image](https://github.com/otavepto/gbe_fork/assets/39947399/e2794a78-3bf2-42a3-b40e-0502cd51a5cf)

**Comment by Kola124** [comment]
Serious Sam Classic Revolution, Tabletop Simulator, Pummel Party work

Call to Arms still nothing: 
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/14003000/STEAM_LOG.txt)
![image](https://github.com/otavepto/gbe_fork/assets/39947399/a22f52c8-3f26-426e-a3a5-dde184efb174)

Serious Sam Fusion gives this 
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/14003003/STEAM_LOG.txt)
![image](https://github.com/otavepto/gbe_fork/assets/39947399/32fb05f2-0c93-418c-8849-5010f1d13d29)

**Comment by BTFighter** [comment]
The artifacts expired. Can anybody send a copy of the build? Thanks in advance,

**Comment by Detanup01** [comment]
https://github.com/otavepto/gbe_fork/releases/tag/release-2024-1-20-workshop-inject-dlls
This is the last build

**Comment by Detanup01** [comment]
Serious Sam Fusion:
It doesnt send anything to download or update anything.
Maybe GetItemInstallInfo doing wierd things????

Call to Arms:
as I see everything works as expected

**Comment by Detanup01** [comment]
:D Nice.
Now I think I would make a secound release with the fixed stuff (in my opinion)

**Comment by Detanup01** [comment]
Idk but probably should, don't own that game so can't say about it.

**Comment by Kola124** [comment]
I see you made some changes now, will test in evening, but last time i tested 2 days ago everything was same. 

This is becoming too much resource sink while there are better things to do, it would probably be better to do something else and leave this on sidelines for when 99% of stuff is done.

**Comment by BTFighter** [comment]
I agree, Human Fall Flat works now as well so I think this issue can be closed. It will be up to you guys though.

![image](https://github.com/otavepto/gbe_fork/assets/45516471/328f9ef1-903c-4195-8d62-475fc98fa4d7)

**Comment by Detanup01** [comment]
Thank y'all for testing!
@otavepto can be closed :)
